"""Apply English strings to order_executor.py (run once)."""
from pathlib import Path
p = Path(__file__).resolve().parent.parent / "AI Bot" / "order_executor.py"
s = p.read_text(encoding="utf-8")
REPL = [
    ('"""Binance -1021 timestamp hatasi mi kontrol eder."""', '"""Detect Binance -1021 timestamp error."""'),
    ('"""Gecici API hatalari (retry edilebilir)."""', '"""Transient API errors (retryable)."""'),
    ('"""Binance -2011 UNKNOWN_ORDER - emir zaten kapanmis/iptal."""', '"""Binance -2011 UNKNOWN_ORDER — order already gone."""'),
    ('"""fetch_ticker ile gecici API hatalarinda retry."""', '"""fetch_ticker with retry on transient errors."""'),
    ('"""Binance sunucu saatini cekerek CCXT offset\'ini tazeler."""', '"""Refresh CCXT time offset from Binance server time."""'),
    ('"""Market emrinin ortalama fill fiyatini doner."""', '"""Average fill price for a market order."""'),
    ('"""Runtime config\'den TP/SL yuzde degerlerini alir."""', '"""TP/SL percentages from runtime config."""'),
    ('"""Binance USDT-M Futures Exchange objesi olusturur"""', '"""Create Binance USDT-M futures exchange."""'),
    ('"""Sembolu binanceusdm formatina cevirir. \'BTC/USDT\' -> \'BTC/USDT:USDT\'"""',
     '"""Normalize symbol for binanceusdm (e.g. BTC/USDT -> BTC/USDT:USDT)."""'),
    ('"""Bakiye bilgisini ceker"""', '"""Fetch wallet balance."""'),
    ('Bakiye cekilemedi:', 'Balance fetch failed:'),
    ('"""Kaldirac ayarlar (Sadece Futures)"""', '"""Set leverage (futures only)."""'),
    ('Kaldirac ayarlandi:', 'Leverage set:'),
    ('Kaldirac ayarlanamadi', 'Leverage failed'),
    ('"""AUTO_TRADE ve runtime_config kontrolu yapar."""', '"""Check AUTO_TRADE and runtime_config."""'),
    ('    Islem emri gonderir ve TP/SL emirlerini Binance\'a koyar.\n    Donus:', '    Send order and place TP/SL on Binance.\n    Returns:'),
    ('Yeni islem almak durduruldu - sinyal alinmadi:', 'New trades disabled — skipping:'),
    ('Yetersiz Bakiye veya Min Limit Alti:', 'Insufficient balance or below min:'),
    ('Spot piyasada Short acilamaz.', 'Cannot open short on spot.'),
    ('GERCEK BINANCE ISLEMI - EMIR GONDERILIYOR', 'LIVE BINANCE - SENDING ORDER'),
    ('GERCEK BINANCE ISLEMI - ISLEM BASARILI!', 'LIVE BINANCE - ORDER FILLED!'),
    ('Miktar:', 'Qty:'),
    ('GERCEK BINANCE - Fill fiyati:', 'LIVE BINANCE - Fill price:'),
    ('(sinyal:', '(signal:'),
    ('Zaman senkronizasyonu hatasi,', 'Time sync error,'),
    ('sn sonra tekrar deneniyor...', 's, retrying...'),
    ('Islem Hatasi:', 'Trade error:'),
    ('Sistem saatinizi Internet Time ile senkronize edin', 'Sync system clock with internet time'),
    ('    Binance Futures\'a Stop Loss ve Take Profit emirlerini koyar.\n    reduceOnly=True + amount: Sadece bu trade\'in miktarini kapatir.\n    Diger trade\'lerin emirlerine dokunmaz.',
     '    Place SL/TP on Binance Futures.\n    reduceOnly+amount closes only this trade size.'),
    ('SL Buffer uygulandi', 'SL buffer applied'),
    ('SL buffer uygulama hatasi:', 'SL buffer error:'),
    ('SL Emri Konuldu', 'SL order placed'),
    ('SL emri konulamadi:', 'SL order failed:'),
    ('TP Emri Konuldu', 'TP order placed'),
    ('TP emri konulamadi:', 'TP order failed:'),
    ('emir iptal edildi', 'order cancelled'),
    ('emir zaten kapanmis/iptal', 'order already closed/cancelled'),
    ('emir iptal hatasi', 'order cancel error'),
    ('    TP1 hit oldugunda belirli trade\'in SL\'ini breakeven\'e cevirir.',
     '    Move SL to breakeven after TP1 for a specific trade.'),
    ('Eski SL iptal edildi', 'Old SL cancelled'),
    ('Eski SL zaten kapanmis', 'Old SL already gone'),
    ('Eski SL iptal hatasi', 'Old SL cancel error'),
    ('BE Buffer uygulandi', 'BE buffer applied'),
    ('BE buffer uygulama hatasi:', 'BE buffer error:'),
    ('Yeni SL (Breakeven, reduceOnly):', 'New SL (breakeven, reduceOnly):'),
    ('Binance propagasyon gecikmesi (-4130),', 'Binance propagation delay (-4130),'),
    ('sn bekleniyor...', 's waiting...'),
    ('SL guncelleme hatasi:', 'SL update error:'),
    ('    Belirli miktari kapatir (reduceOnly market order).\n    Pozisyonun sadece bir parcasini kapatmak icin kullanilir.',
     '    Close partial size (reduceOnly market).'),
    ('Kismi pozisyon kapatildi:', 'Partial close:'),
    ('Kismi pozisyon kapatma hatasi:', 'Partial close error:'),
    ('    Bir sembol icin tum acik emirleri iptal eder ve dogrular.',
     '    Cancel and verify all open orders for a symbol.'),
    ('Toplu iptal cagrildi', 'Batch cancel called'),
    ('basarili', 'ok'),
    ('Toplu iptal basarisiz', 'Batch cancel failed'),
    ('Algo iptal hatasi:', 'Algo cancel error:'),
    ('Emirler temizlendi (toplu iptal)', 'Orders cleared (batch cancel)'),
    ('Acik emir yok, temiz', 'No open orders'),
    ('Tekil iptal hatasi', 'Single cancel error'),
    ('emir iptal edildi', 'orders cancelled'),
    ('print(f"UYARI: {symbol} icin {len(remaining_target)} emir hala temizlenemedi!")',
     'print(f"WARNING: {symbol}: {len(remaining_target)} orders still not cleared!")'),
    ('Dogrulama:', 'Verified:'),
    ('tum emirler temizlendi', 'all orders cleared'),
    ('API hatasi (emir iptal),', 'API error (cancel),'),
    ('Emir iptal hatasi (tum denemeler basarisiz):', 'Cancel failed after retries:'),
    ('"""Binance Futures conditional (algo) emirlerini iptal eder."""',
     '"""Cancel Binance Futures conditional (algo) orders."""'),
    ('Algo emir listesi alinamadi', 'Algo order list failed'),
    ('algo (conditional) emir iptal edildi', 'algo (conditional) orders cancelled'),
    ('    Acik pozisyonu kapatir ve ilgili TP/SL emirlerini iptal eder.',
     '    Close position and cancel related TP/SL.'),
    ('Emir iptal problemi:', 'Order cancel issue:'),
    ('POZISYON KAPATILIYOR:', 'CLOSING POSITION:'),
    ('Pozisyon Kapatildi.', 'Position closed.'),
    ('Pozisyon zaten Binance tarafindan kapatilmis (SL/TP tetiklendi).',
     'Position already closed by Binance (SL/TP hit).'),
    ('Pozisyon zaten Binance tarafindan kapatilmis.', 'Position already closed by Binance.'),
    ('Zaman senkronizasyonu hatasi (kapatma),', 'Time sync error (close),'),
    ('Pozisyon kapatma hatasi:', 'Close position error:'),
]
for old, new in sorted(REPL, key=lambda x: len(x[0]), reverse=True):
    s = s.replace(old, new)
p.write_text(s, encoding="utf-8")
print('done')
